apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: e2etracking
spec:
  selector:
    matchLabels:
      app: e2etracking
  replicas: 1 # comment - tells deployment to run 1 pods matching the template 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: e2etracking
    spec:
      containers:
      - name: e2etracking
        image: mkadocker/e2etracking:BUILD_ID_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8092
          name: server
        - containerPort: 8093
          name: management
        env:
        - name: NGOI_DATABASE
          valueFrom:
            configMapKeyRef:
              name: transactiondataservice
              key: database-name
        - name: NGOI_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: transactiondataservice
              key: database-user
        - name: NGOI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transactiondataservice
              key: database-password
   
        