apiVersion: v1
kind: Service
metadata:
  name: e2etracking
spec:
  ports:
  - port: 8092
    targetPort: 8092
    name: http
  - port: 8093
    targetPort: 8093
    name: management
  selector:
    app: e2etracking
  type: LoadBalancer